# Generated by Django 3.0 on 2022-09-04 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 19, 56, 26, 307805, tzinfo=utc)),
        ),
    ]
