# Generated by Django 3.0 on 2022-09-06 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20220904_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 20, 20, 51, 589198, tzinfo=utc)),
        ),
    ]
