# Generated by Django 3.0 on 2022-09-06 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20220906_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 20, 40, 23, 944611, tzinfo=utc)),
        ),
    ]
